# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Build MOD DEMO

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      #      - name: Run DataGen
      #        run: gradle runData -q
      #
      #      - name: Push
      #        if: always()
      #        run: |
      #          git config --global user.name DataGenCI
      #          git add .
      #          git reset --mixed settings.xml
      #          git reset --mixed toolchains.xml
      #          git commit -m "datagen" -a
      #          git push

      #      - name: Cache
      #        uses: actions/cache@v3
      #        with:
      #          path: build/**/*
      #          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      #          restore-keys: |
      #            ${{ runner.os }}-gradle-
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.3

      - name: Setup Permissions
        run: chmod +x gradlew

      - name: Execute Gradle build
        run: ./gradlew build -PCIBuildVersion=.${{ github.run_number }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Kitchenkarrot-${{ github.sha }}
          path: build/libs/*.jar